export const paths = {
  index: '/',
  blank: '/blank',
  docs: 'https://material-kit-pro-react-docs.devias.io',
  home: '/',
  event: "/event",
  ranking: '/ranking',
  faq: '/faq',
  news: '/news',
  commitments: "/commitments",
  plan: '/plan',
  contactUs: '/contact-us',
  blog: `news/blog`,
  privacyPolicy: '/privacy-policy',
  termsConditions: '/terms-conditions',
};
